### ISSUE TITLE
Allow to set git blame options

### ISSUE THREAD

**Issue by chocilini** [guillaumeaubert/Git-Repository-Plugin-Blame#7]
I'd like to have the possibility to ignore whitespaces while blaming. Maybe you could provide a way to set options when calling $repository->blame(). These should only be added to the command call.

**Comment by guillaumeaubert** [comment]
Excellent addition - thank you, @chocilini!

I modified Git::Repository::Plugin::Blame::Cache to account for the possibility of having options that modify `blame()`'s output and cache them separately, as well as added tests to specifically cover ignore_whitespace and documented this new option in the POD.

Released with v1.3.0.

**Comment by chocilini** [comment]
Thank you for your quick reaction and for adding the documentation and tests!
